name: S3_Build

on:
  push:
    branches: [ actions, main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.11.0'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Run Build
        run: |
          yarn build
      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: branch
      - name: Choose S3 Environment
        id: get_env
        env:
          BRANCH_NAME: ${{ steps.branch.outputs.branch }}
        run: |
          if [ "${BRANCH_NAME}" == "main" ]; then
          echo "::set-output name=environment_name::${{ secrets.AWS_BUCKET_PROD }}"
          fi
          if [ "${BRANCH_NAME}" == "develop" ]; then
          echo "::set-output name=environment_name::${{ secrets.AWS_BUCKET_DEV }}"
          fi
          if [[ "${BRANCH_NAME}" == "stage" ]] || [[ "${BRANCH_NAME:0:8}" == "staging/" ]]; then
          echo "::set-output name=environment_name::${{ secrets.AWS_BUCKET_STAGE }}"
          fi
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy static site to S3 bucket 
        run: aws s3 sync ./build s3://${{ steps.get_env.outputs.environment_name }} --delete